export const clubes = [
'Barcelona',
'Real Madrid',
'Atletico Madrid',
'Sevilla',
'Valencia',
'Manchester United',
'Manchester City',
'Liverpool',
'Chelsea',
'Arsenal',
'Tottenham',
'Bayern Munich',
'Borussia Dortmund',
'RB Leipzig',
'PSG',
'Olympique de Marseille',
'Olympique Lyon',
'Juventus',
'Inter',
'Milan',
'Napoli',
'Roma',
'Benfica',
'Porto',
'Sporting Lisboa',
'Ajax',
'PSV Eindhoven',
'Feyenoord',
'Boca Juniors',
'River Plate',
'Racing Club',
'Independiente',
'San Lorenzo',
'Newell s',
'Rosario Central',
'Santos',
'Sao Paulo',
'Flamengo',
'Palmeiras',
'Corinthians',
'Gremio',
'Liga de Quito',
'Colo Colo',
'Universidad de Chile',
'Peñarol',
'Nacional',
'LA Galaxy',
'New York City FC',
'Tigres',
'America de Mexico'
]