 const futbolH = [
    'Diego Maradona',
    'Pelé',
    'Johan Cruyff',
    'Zinedine Zidane',
    'Ronaldo Nazario',
    'Ronaldinho',
    'David Beckham',
    'Francesco Totti',
    'Paolo Maldini',
    'Andrea Pirlo',
    'Xavi Hernández',
    'Xavi Alonso',
    'Andrés Iniesta',
    'Carlos Tévez',
    'Juan Roman Riquelme',
    'Gabriel Batistuta',
    'Hernán Crespo',
    'Raúl Gonzalez',
    'Iker Casillas',
    'Carles Puyol',
    'Fernando Torres',
    'Thierry Henry',
    'Didier Drogba',
    'Samuel Etoo',
    'Kaka',
    'Roberto Carlos',
    'Cafú',
    'Rivaldo',
    'Gianluigi Buffon',
    'Oliver Kahn',
    'Miroslav Klose',
    'Mesut Ozil',
    'Arjen Robben',
    'Frank Lampard',
    'Steven Gerrard',
    'Wayne Rooney',
    'Ryan Giggs',
    'Paul Scholes',
    'Alan Shearer',
    'Eric Cantona',
    'George Best',
    'Marco van Basten',
    'Ruud Gullit',
    'Bastian Schweinsteiger',
    'Philipp Lahm',
    'Claude Makelele',
    'Pavel Nedved',
    'Michael Ballack',
    'Dani Alves',
    'Diego Forlán',
    'Jose Luis Chilavert',
    'Toni Kross',
    'Luka Modric',
    'Lionel Messi',
    'Cristiano Ronaldo',
    'Neymar'
];