export const futbolH = [
    'Diego Maradona',
    'Pele',
    'Johan Cruyff',
    'Zinedine Zidane',
    'Ronaldo Nazario',
    'Ronaldinho',
    'David Beckham',
    'Francesco Totti',
    'Paolo Maldini',
    'Andrea Pirlo',
    'Xavi Hernandez',
    'Andres Iniesta',
    'Carlos Tevez',
    'Juan Roman Riquelme',
    'Gabriel Batistuta',
    'Hernan Crespo',
    'Raul Gonzalez',
    'Iker Casillas',
    'Carles Puyol',
    'Fernando Torres',
    'Thierry Henry',
    'Didier Drogba',
    'Samuel Etoo',
    'Kaka',
    'Roberto Carlos',
    'Cafu',
    'Rivaldo',
    'Gianluigi Buffon',
    'Oliver Kahn',
    'Miroslav Klose',
    'Mesut Ozil',
    'Arjen Robben',
    'Frank Lampard',
    'Steven Gerrard',
    'Wayne Rooney',
    'Ryan Giggs',
    'Paul Scholes',
    'Alan Shearer',
    'Eric Cantona',
    'George Best',
    'Marco van Basten',
    'Ruud Gullit',
    'Bastian Schweinsteiger',
    'Philipp Lahm',
    'Claude Makelele',
    'Pavel Nedved',
    'Michael Ballack',
    'Dani Alves',
    'Diego Forlan',
    'Jose Luis Chilavert'
];
