Lionel-Messi
Cristiano-Ronaldo
Kylian-Mbappe
Erling-Haaland
Neymar-Jr
Kevin-De-Bruyne
Mohamed-Salah
Harry-Kane
Vinícius-Jr
Jude-Bellingham
Rodri
Antoine-Griezmann
Pedri
Gavi
Robert-Lewandowski
Karim-Benzema
Luka-Modric
Toni-Kroos
Marc-Andre-ter-Stegen
Thibaut-Courtois
Jan-Oblak
Virgil-van-Dijk
Trent-Alexander-Arnold
Andrew-Robertson
Bukayo-Saka
Phil-Foden
Bruno-Fernandes
Marcus-Rashford
Joao-Felix
Rafael-Leao
Son-Heung-min
Federico-Valverde
Lautaro-Martinez
Enzo-Fernandez
Julian-Alvarez
Angel-Di-Maria
Paulo-Dybala
Riyad-Mahrez
Achraf-Hakimi
Jadon-Sancho
Alphonso-Davies
Sergio-Ramos
Gerard-Pique
Raphael-Varane
Ruben-Dias
Joshua-Kimmich
Ilkay-Gundogan
Ousmane-Dembele
Declan-Rice
Bernardo-Silva