export const futbolA = [
'Lionel Messi',
'Cristiano Ronaldo',
'Neymar',
'Kylian Mbappe',
'Erling Haaland',
'Kevin De Bruyne',
'Robert Lewandowski',
'Luka Modric',
'Karim Benzema',
'Vinicius Junior',
'Rodri',
'Pedri',
'Gavi',
'Jude Bellingham',
'Phil Foden',
'Mohamed Salah',
'Sadio Mane',
'Harry Kane',
'Marcus Rashford',
'Bruno Fernandes',
'Antoine Griezmann',
'Ousmane Dembele',
'Joao Felix',
'Lautaro Martinez',
'Julian Alvarez',
'Angel Di Maria',
'Rodrigo De Paul',
'Emiliano Martinez',
'Federico Valverde',
'Darwin Nunez',
'Luis Diaz',
'Rafael Leao',
'Son Heung-min',
'Hakim Ziyech',
'Achraf Hakimi',
'Riyad Mahrez',
'Christian Pulisic',
'Alphonso Davies',
'Joshua Kimmich',
'Antonio Rudiger',
'Virgil Van Dijk',
'Trent Alexander-Arnold',
'Andrew Robertson',
'Pau Torres',
'Pedrinho',
'Paulo Dybala',
'Enzo Fernandez',
'Alejandro Garnacho',
'Rodrygo'
]