const futbolA = [
'Lionel Messi',
'Cristiano Ronaldo',
'Neymar',
'Kylian Mbappe',
'Erling Haaland',
'Kevin De Bruyne',
'Robert Lewandowski',
'Luka Modric',
'Karim Benzema',
'Vinicius Junior',
'Rodri',
'Pedri',
'Gavi',
'Jude Bellingham',
'Phil Foden',
'Mohamed Salah',
'Sadio Mané',
'Harry Kane',
'Marcus Rashford',
'Bruno Fernándes',
'Antoine Griezmann',
'Ousmane Dembélé',
'Joao Félix',
'Lautaro Martínez',
'Julian Álvarez',
'Ángel Di María',
'Rodrigo De Paul',
'Emiliano Martínez',
'Federico Valverde',
'Darwin Nuñez',
'Luis Díaz',
'Rafael Leao',
'Son Heung-min',
'Hakim Ziyech',
'Achraf Hakimi',
'Riyad Mahrez',
'Christian Pulisic',
'Alphonso Davies',
'Joshua Kimmich',
'Antonio Rudiger',
'Virgil Van Dijk',
'Trent Alexander-Arnold',
'Andrew Robertson',
'Pau Torres',
'Cavani',
'Leandro Paredes',
'Paulo Dybala',
'Enzo Fernández',
'Alejandro Garnacho',
'Rodrygo'
]